# Generated by Django 4.2.29 on 2026-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_lat', models.FloatField(default=23.685)),
                ('center_lng', models.FloatField(default=90.356)),
                ('zoom', models.IntegerField(default=7)),
                ('base_layer', models.CharField(default='osm', max_length=50)),
                ('layer_state', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
