# Generated by Django 4.2.29 on 2026-03-07 18:54

import apps.layers.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('raster', 'Raster (GeoTIFF/IMG)'), ('vector', 'Vector (SHP/GeoJSON/KML)'), ('geojson', 'GeoJSON')], max_length=20)),
                ('file', models.FileField(upload_to=apps.layers.models.layer_upload_path)),
                ('aux_files', models.JSONField(blank=True, default=list)),
                ('bbox_west', models.FloatField(blank=True, null=True)),
                ('bbox_south', models.FloatField(blank=True, null=True)),
                ('bbox_east', models.FloatField(blank=True, null=True)),
                ('bbox_north', models.FloatField(blank=True, null=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('visible', models.BooleanField(default=True)),
                ('z_index', models.IntegerField(default=0)),
                ('style_config', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('geojson_cache', models.FileField(blank=True, null=True, upload_to='layers/cache/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
    ]
