# Generated by Django 4.2.29 on 2026-05-07 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When locked, only admins can change style/opacity/etc.'),
        ),
        migrations.AddField(
            model_name='layer',
            name='outline_color',
            field=models.CharField(default='#29b6f6', max_length=20),
        ),
        migrations.AddField(
            model_name='layer',
            name='outline_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='outline_weight',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_layers', to=settings.AUTH_USER_MODEL),
        ),
    ]
